language: node_js
node_js:
- 5.2.0
before_install:
- npm install npm-prepublish
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  # NPM_EMAIL
  - secure: "QCGEsS3Tv55jvcQ7fEJpyiSyJhcx3YlFoSRYyyYeHIzcYUkHBooDGlCPcI3IloyFPHl67snbVqRereqqfOPj3JE15vZKHGmapvwzPTjDOMuyp1SKTi7MiBybhsFUO4cOKL0afO+c37xcuz1QlZKMk8SQAEDuNxpzAhI6dEzR7hCTeUrDsFTvo6RQk/zjGn4h8x1BY2CZNSx+ZBXq41DCyAYTFuqj8x7VDepOW542CmyOznqrgfvJCY1r9v/iSJF6iO1Hn+r0Ftqr5J6DVr6eJ8aG04l1dc6SbNeSr6COmorHX9HLaWZIndskCXepfP9Ddzst0VVk0c3rBCseS3EIkJcyk8v3e1iEX8kENZ4vcIlVGNKR7YsuwybZik0yGW2JStdMaytLfBk6ekNqaYArA1bpqGobqDRJghOGzm2AIj5dwD1s0I+Sb/6RhtTNNSufciKYHeyMjM5d+5ymqbh8UfOcKxdZw7J+bU6ihkefWUwKQCYwL15OtPW1G/hZypyk+8LfIySsUGRNOUuqtaZhn9Ap9C3yEp2bqlmLGFOy6ac9Ya+TFofUalJfnxpVgYlIN9M3Ao8X0W9KsU0v9BV8zNtcwACcpUknpze3N+8fD+OrYA6+WegyG/FKsQZ2wSScyji9c6aAS9AbSYfSGQ1IANomJlK2d7rD6Rft+2zc47Y="
  #NPM_API_KEY
  - secure: "fFn1MAy5wFMPvpdWH2fWwShiCrYt699C1CUYvC8irlvVfzJQ99l3JfGXGzIKpviHqCxOX7fqgG884qYrsdNQKHKsK5SM+OVkK75l7Ry9TzKed0ZFkZ8ZokImUTIqJRMhQZNcy6tu/BvmZk1j1uFLZ2hDDpwEkAs8xttGe0z2QMZnRAt5vnjfzr82z1OdRlRYUFL92WLRm5qlfvVUfEBOqfMOY3mNIGBzTPVVPWj+JVrj7FJ0tlf/FIfIFBpLBDCg+YOO28hLPhcZeArMYze34Ez3FAsHMyJmhJrhChUWd7NY4I2MVgho9CnN2/BuypjjHMzLUGA3rL3VCeFB0F3q6RFtUlIKZVIjTJzmP1HxWUwXJenCPcFLZRtx5TC0uIICbk92yOmW6i1PI4545Gs7udvNeO7tS9SDlNcdUdeDoz7tTUpjthFwmhjIq42qA2mCKWC9hijrS/TvuevrpyL/VLUA/0ocFD5LkBo1gjmHC5S/pEkmt0g8gZxne2yUmylIpIGsZyI1S5Y8G09AlxdD5nqxd93mrTZNCEeEc6KYoyVucaJ5HpMN6CLHKc+K46vvtT6v7nKqrp7ztrZhA1iwnMeZaonfc3Us/Ky+f2VZdHY7+JbYNhgx1/2amq57UswlBCSyR9JqVgH3AgRnwL8+rk51tQ7AAjmm89fG3uN5el0="
